categories: "Categorías"
search: "Búsqueda"
tags: "Tags"
tagcloud: "Tag Cloud"
tweets: "Tweets"
prev: "Prev"
next: "Next"
comment: "Comments"
archive_a: "Archivo"
archive_b: "Archivo: %s"
page: "Página %d"
recent_posts: "Publicaciones Recientes"
