menu:
  Eventos: http://meetup.com/costaricajs
  Archivos: /archivo

widgets:
- search
- category
- tag
- twitter

excerpt_link: leer el artículo completo

github:
  username:  costaricajs

twitter:
  username: costaricajs
  show_replies: false
  tweet_count: 5

google_analytics: UA-33524638-2
domain: http://costaricajs.github.io

rss: http://feeds.feedburner.com/costaricajs
